#!/usr/bin/env pwsh
# build-wasm.ps1
#
# Builds every helio-web-demos WASM demo and runs wasm-bindgen on each.
#
# HTML landing pages are generated automatically by the crate's build.rs and
# written to target/wasm-prebuilt/<name>/index.html — no HTML work needed here.
#
# Outputs land in:  target/wasm-prebuilt/<name>/
#   index.html          <- generated by build.rs
#   helio_web_demos.js  <- wasm-bindgen JS shim
#   helio_web_demos_bg.wasm
#
# Usage:
#   ./build-wasm.ps1                    # build all demos
#   ./build-wasm.ps1 ship_flight        # build one demo
#   ./build-wasm.ps1 --release          # use release profile (default)
#   ./build-wasm.ps1 --dev ship_flight  # use dev profile

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Push-Location $root

$wasm_target = "wasm32-unknown-unknown"

# Parse flags
$profile     = "release"
$filter_name = $null
foreach ($arg in $args) {
    if ($arg -eq "--dev")     { $profile = "debug" }
    elseif ($arg -eq "--release") { $profile = "release" }
    else                      { $filter_name = $arg }
}

$all_examples = @(
    "render_v2_basic",
    "render_v2_sky",
    "debug_shapes",
    "indoor_room",
    "indoor_corridor",
    "outdoor_night",
    "outdoor_canyon",
    "indoor_cathedral",
    "indoor_server_room",
    "outdoor_city",
    "outdoor_volcano",
    "space_station",
    "light_benchmark",
    "rc_benchmark",
    "load_fbx",
    "load_fbx_embedded",
    "ship_flight",
    "simple_graph",
    "outdoor_rocks",
    "editor_demo"
)

if ($filter_name) {
    if ($all_examples -notcontains $filter_name) {
        Write-Error "Unknown demo '$filter_name'. Valid: $($all_examples -join ', ')"
        exit 1
    }
    $examples = @($filter_name)
} else {
    $examples = $all_examples
}

$wasm_lib_name = "helio_web_demos"
$failed = @()

foreach ($name in $examples) {
    Write-Host ""
    Write-Host "════ $name ════" -ForegroundColor Cyan

    $out_dir = Join-Path $root "target" "wasm-prebuilt" $name
    New-Item -ItemType Directory -Force -Path $out_dir | Out-Null

    # cargo build  (build.rs runs here, generating HTML into OUT_DIR and
    # copying index.html into target/wasm-prebuilt/<name>/ automatically)
    $cargo_args = @(
        "build", "--lib",
        "-p", "helio-web-demos",
        "--target", $wasm_target,
        "--no-default-features",
        "--features", $name
    )
    if ($profile -eq "release") { $cargo_args += "--release" }

    Write-Host "  cargo $($cargo_args -join ' ')"
    & cargo @cargo_args
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  FAILED cargo build for $name" -ForegroundColor Red
        $failed += $name
        continue
    }

    $wasm_path = Join-Path $root "target" $wasm_target $profile "${wasm_lib_name}.wasm"
    if (-not (Test-Path $wasm_path)) {
        Write-Host "  FAILED: wasm not found at $wasm_path" -ForegroundColor Red
        $failed += $name
        continue
    }
    $wasm_size = (Get-Item $wasm_path).Length
    Write-Host "  wasm OK ($([math]::Round($wasm_size/1MB, 2)) MiB)"

    Write-Host "  wasm-bindgen -> $out_dir"
    wasm-bindgen $wasm_path --out-dir $out_dir --target web
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  FAILED wasm-bindgen for $name" -ForegroundColor Red
        $failed += $name
        continue
    }

    Write-Host "  OK -> $out_dir" -ForegroundColor Green
}

Write-Host ""
if ($failed.Count -gt 0) {
    Write-Host "FAILED: $($failed -join ', ')" -ForegroundColor Red
    exit 1
} else {
    Write-Host "All $($examples.Count) demo(s) built." -ForegroundColor Green
    Write-Host ""
    Write-Host "Serve with any static file server, e.g.:"
    Write-Host "  npx serve target/wasm-prebuilt" -ForegroundColor Yellow
}
