#!/usr/bin/env bash
# build-wasm.sh
#
# Builds every helio-web-demos WASM demo and runs wasm-bindgen on each.
#
# HTML landing pages are generated automatically by the crate's build.rs and
# written to target/wasm-prebuilt/<name>/index.html — no HTML work needed here.
#
# Outputs land in:  target/wasm-prebuilt/<name>/
#   index.html          <- generated by build.rs
#   helio_web_demos.js  <- wasm-bindgen JS shim
#   helio_web_demos_bg.wasm
#
# Usage:
#   ./build-wasm.sh                   # build all demos (release)
#   ./build-wasm.sh ship_flight       # build one demo
#   ./build-wasm.sh --dev             # dev profile
#   ./build-wasm.sh --dev ship_flight

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

WASM_LIB_NAME="helio_web_demos"
PROFILE="release"
FILTER_NAME=""

# ── Prerequisite checks ─────────────────────────────────────────────────────

check_wasm_pack() {
    if ! command -v wasm-pack >/dev/null 2>&1; then
        echo "wasm-pack not found.  Install it with:" >&2
        echo "  cargo install wasm-pack" >&2
        exit 1
    fi
}

check_cc_wasm() {
    # meshopt and other C/C++ deps need a clang with the wasm32 target.
    # macOS system clang doesn't include it.  Check for LLVM from Homebrew.
    local cc="${CC:-cc}"
    echo 'int x;' > /tmp/wasm_cc_test.c
    if ! $cc --target=wasm32-unknown-unknown -c /tmp/wasm_cc_test.c -o /tmp/wasm_cc_test.o 2>/dev/null; then
        if command -v "$(brew --prefix llvm 2>/dev/null)/bin/clang" >/dev/null 2>&1; then
            export CC="$(brew --prefix llvm)/bin/clang"
            echo "  Using LLVM clang at $CC"
        else
            echo "C compiler '$cc' cannot target wasm32-unknown-unknown." >&2
            echo "" >&2
            echo "Install a wasm-capable LLVM:" >&2
            echo "  brew install llvm" >&2
            echo "  export CC=\"\$(brew --prefix llvm)/bin/clang\"" >&2
            echo "" >&2
            echo "Then re-run this script." >&2
            exit 1
        fi
    fi
    rm -f /tmp/wasm_cc_test.c /tmp/wasm_cc_test.o
}

check_wasm_pack
check_cc_wasm

# Parse flags
for arg in "$@"; do
    case "$arg" in
        --dev)     PROFILE="debug" ;;
        --release) PROFILE="release" ;;
        *)         FILTER_NAME="$arg" ;;
    esac
done

declare -a ALL_EXAMPLES=(
    render_v2_basic
    render_v2_sky
    debug_shapes
    indoor_room
    indoor_corridor
    outdoor_night
    outdoor_canyon
    indoor_cathedral
    indoor_server_room
    outdoor_city
    outdoor_volcano
    space_station
    light_benchmark
    hlfs_benchmark
    sdf_demo
    rc_benchmark
    load_fbx
    load_fbx_embedded
    ship_flight
    simple_graph
    outdoor_rocks
    editor_demo
)

if [[ -n "$FILTER_NAME" ]]; then
    found=0
    for ex in "${ALL_EXAMPLES[@]}"; do [[ "$ex" == "$FILTER_NAME" ]] && found=1; done
    if [[ $found -eq 0 ]]; then
        echo "Unknown demo '$FILTER_NAME'. Valid: ${ALL_EXAMPLES[*]}" >&2
        exit 1
    fi
    EXAMPLES=("$FILTER_NAME")
else
    EXAMPLES=("${ALL_EXAMPLES[@]}")
fi

[[ "$PROFILE" == "release" ]] && PROFILE_FLAG="--release" || PROFILE_FLAG=""

FAILED=()

for name in "${EXAMPLES[@]}"; do
    echo ""
    echo "════ $name ════"

    out_dir_abs="$SCRIPT_DIR/target/wasm-prebuilt/$name"
    mkdir -p "$out_dir_abs"

    wasm_profile_flag=""
    [[ "$PROFILE" == "release" ]] && wasm_profile_flag="--release"

    if ! (
        cd crates/helio-web-demos &&
        CC="$CC" wasm-pack build \
            $wasm_profile_flag \
            --target web \
            --no-default-features \
            --features "$name"
    ); then
        echo "  FAILED wasm-pack build for $name" >&2
        FAILED+=("$name")
        continue
    fi
    rm -rf "$out_dir_abs" &&
    mv crates/helio-web-demos/pkg "$out_dir_abs" &&
    echo "  moved pkg/ -> $out_dir_abs"

    wasm_path="$out_dir_abs/${WASM_LIB_NAME}_bg.wasm"
    if [[ -f "$wasm_path" ]]; then
        wasm_mib=$(( $(wc -c < "$wasm_path") / 1048576 ))
        echo "  wasm OK (~${wasm_mib} MiB) -> $out_dir_abs"
    else
        echo "  FAILED: wasm not found at $wasm_path" >&2
        FAILED+=("$name")
        continue
    fi
done

echo ""
if [[ ${#FAILED[@]} -gt 0 ]]; then
    echo "FAILED: ${FAILED[*]}" >&2
    exit 1
else
    echo "All ${#EXAMPLES[@]} demo(s) built."
    echo ""
    echo "Serve with any static file server, e.g.:"
    echo "  npx serve target/wasm-prebuilt"
fi
