#!/usr/bin/env bash
# build-wasm.sh
#
# Builds every helio-web-demos WASM demo and runs wasm-bindgen on each.
#
# HTML landing pages are generated automatically by the crate's build.rs and
# written to target/wasm-prebuilt/<name>/index.html — no HTML work needed here.
#
# Outputs land in:  target/wasm-prebuilt/<name>/
#   index.html          <- generated by build.rs
#   helio_web_demos.js  <- wasm-bindgen JS shim
#   helio_web_demos_bg.wasm
#
# Usage:
#   ./build-wasm.sh                   # build all demos (release)
#   ./build-wasm.sh ship_flight       # build one demo
#   ./build-wasm.sh --dev             # dev profile
#   ./build-wasm.sh --dev ship_flight

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

WASM_TARGET="wasm32-unknown-unknown"
WASM_LIB_NAME="helio_web_demos"
PROFILE="release"
FILTER_NAME=""

# Parse flags
for arg in "$@"; do
    case "$arg" in
        --dev)     PROFILE="debug" ;;
        --release) PROFILE="release" ;;
        *)         FILTER_NAME="$arg" ;;
    esac
done

declare -a ALL_EXAMPLES=(
    render_v2_basic
    render_v2_sky
    debug_shapes
    indoor_room
    indoor_corridor
    outdoor_night
    outdoor_canyon
    indoor_cathedral
    indoor_server_room
    outdoor_city
    outdoor_volcano
    space_station
    light_benchmark
    rc_benchmark
    load_fbx
    load_fbx_embedded
    ship_flight
    simple_graph
    outdoor_rocks
    editor_demo
)

if [[ -n "$FILTER_NAME" ]]; then
    found=0
    for ex in "${ALL_EXAMPLES[@]}"; do [[ "$ex" == "$FILTER_NAME" ]] && found=1; done
    if [[ $found -eq 0 ]]; then
        echo "Unknown demo '$FILTER_NAME'. Valid: ${ALL_EXAMPLES[*]}" >&2
        exit 1
    fi
    EXAMPLES=("$FILTER_NAME")
else
    EXAMPLES=("${ALL_EXAMPLES[@]}")
fi

[[ "$PROFILE" == "release" ]] && PROFILE_FLAG="--release" || PROFILE_FLAG=""

FAILED=()

for name in "${EXAMPLES[@]}"; do
    echo ""
    echo "════ $name ════"

    out_dir="$SCRIPT_DIR/target/wasm-prebuilt/$name"
    mkdir -p "$out_dir"

    # cargo build  (build.rs writes index.html to $out_dir automatically)
    echo "  cargo build $PROFILE_FLAG --lib -p helio-web-demos --features $name"
    if ! cargo build $PROFILE_FLAG --lib \
        -p helio-web-demos \
        --target "$WASM_TARGET" \
        --no-default-features \
        --features "$name"; then
        echo "  FAILED cargo build for $name" >&2
        FAILED+=("$name")
        continue
    fi

    wasm_path="$SCRIPT_DIR/target/$WASM_TARGET/$PROFILE/${WASM_LIB_NAME}.wasm"
    if [[ ! -f "$wasm_path" ]]; then
        echo "  FAILED: wasm not found at $wasm_path" >&2
        FAILED+=("$name")
        continue
    fi
    wasm_mib=$(( $(wc -c < "$wasm_path") / 1048576 ))
    echo "  wasm OK (~${wasm_mib} MiB)"

    echo "  wasm-bindgen -> $out_dir"
    if ! wasm-bindgen "$wasm_path" --out-dir "$out_dir" --target web; then
        echo "  FAILED wasm-bindgen for $name" >&2
        FAILED+=("$name")
        continue
    fi

    echo "  OK -> $out_dir"
done

echo ""
if [[ ${#FAILED[@]} -gt 0 ]]; then
    echo "FAILED: ${FAILED[*]}" >&2
    exit 1
else
    echo "All ${#EXAMPLES[@]} demo(s) built."
    echo ""
    echo "Serve with any static file server, e.g.:"
    echo "  npx serve target/wasm-prebuilt"
fi
