[package]
name = "helio-pass-shadow-dirty"
version = "0.1.0"
edition = "2021"

[dependencies]
helio-core = { workspace = true }
libhelio = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }

[dev-dependencies]
naga = { version = "30.0.0", features = ["wgsl-in"] }
pollster = { workspace = true }
