/// Named resource slot in the render graph, used for dependency declaration.
/// One variant per `FrameResources` tracked field (plus `Depth` for the depth buffer).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ResourceSlot {
    GBuffer,
    GBufferLightmapUv,
    Depth,
    ShadowAtlas,
    StaticShadowAtlas,
    ShadowSampler,
    HiZ,
    HiZSampler,
    StaticHiZ,
    StaticHiZSampler,
    SkyLut,
    SkyLutSampler,
    Ssao,
    PreAa,
    TileLightLists,
    TileLightCounts,
    FullResDepth,
    FullResDepthTexture,
    MainScene,
    Billboards,
    Vg,
    WaterCaustics,
    WaterVolumes,
    WaterSimTexture,
    WaterSimSampler,
    WaterHitboxes,
    DepthTexture,
    BakedAo,
    BakedAoSampler,
    BakedLightmap,
    BakedLightmapSampler,
    BakedReflection,
    BakedReflectionSampler,
    BakedIrradianceSh,
    BakedPvs,
    CoronaEmitters,
}
