//! `helio-web-demos` — every helio example as a WASM binary.
//!
//! Build a specific demo by passing its feature flag:
//!
//! ```sh
//! cargo build --lib -p helio-web-demos \
//!   --target wasm32-unknown-unknown \
//!   --no-default-features --features render_v2_basic
//! wasm-bindgen target/wasm32-unknown-unknown/release/helio_web_demos.wasm \
//!   --out-dir www/render_v2_basic --target web
//! ```
//!
//! Or use the top-level `build-wasm.ps1` / `build-wasm.sh` scripts to
//! build every demo at once.
//!
//! The `html` module exposes compile-time HTML constants generated by
//! `build.rs` — one per demo landing page plus a master `INDEX` listing.

mod common;

// ── Generated HTML pages (build.rs writes these to $OUT_DIR) ─────────────────

/// Compile-time HTML pages generated by `build.rs`.
/// Each constant is the full HTML for that demo's landing page.
/// `INDEX` is the master listing linking to every demo.
pub mod html {
    pub const RENDER_V2_BASIC: &str =
        include_str!(concat!(env!("OUT_DIR"), "/render_v2_basic.html"));
    pub const RENDER_V2_SKY: &str = include_str!(concat!(env!("OUT_DIR"), "/render_v2_sky.html"));
    pub const DEBUG_SHAPES: &str = include_str!(concat!(env!("OUT_DIR"), "/debug_shapes.html"));
    pub const INDOOR_ROOM: &str = include_str!(concat!(env!("OUT_DIR"), "/indoor_room.html"));
    pub const INDOOR_CORRIDOR: &str =
        include_str!(concat!(env!("OUT_DIR"), "/indoor_corridor.html"));
    pub const OUTDOOR_NIGHT: &str = include_str!(concat!(env!("OUT_DIR"), "/outdoor_night.html"));
    pub const OUTDOOR_CANYON: &str = include_str!(concat!(env!("OUT_DIR"), "/outdoor_canyon.html"));
    pub const INDOOR_CATHEDRAL: &str =
        include_str!(concat!(env!("OUT_DIR"), "/indoor_cathedral.html"));
    pub const INDOOR_SERVER_ROOM: &str =
        include_str!(concat!(env!("OUT_DIR"), "/indoor_server_room.html"));
    pub const OUTDOOR_CITY: &str = include_str!(concat!(env!("OUT_DIR"), "/outdoor_city.html"));
    pub const OUTDOOR_VOLCANO: &str =
        include_str!(concat!(env!("OUT_DIR"), "/outdoor_volcano.html"));
    pub const SPACE_STATION: &str = include_str!(concat!(env!("OUT_DIR"), "/space_station.html"));
    pub const LIGHT_BENCHMARK: &str =
        include_str!(concat!(env!("OUT_DIR"), "/light_benchmark.html"));
    pub const RC_BENCHMARK: &str = include_str!(concat!(env!("OUT_DIR"), "/rc_benchmark.html"));
    pub const LOAD_FBX: &str = include_str!(concat!(env!("OUT_DIR"), "/load_fbx.html"));
    pub const LOAD_FBX_EMBEDDED: &str =
        include_str!(concat!(env!("OUT_DIR"), "/load_fbx_embedded.html"));
    pub const SHIP_FLIGHT: &str = include_str!(concat!(env!("OUT_DIR"), "/ship_flight.html"));
    pub const SIMPLE_GRAPH: &str = include_str!(concat!(env!("OUT_DIR"), "/simple_graph.html"));
    pub const OUTDOOR_ROCKS: &str = include_str!(concat!(env!("OUT_DIR"), "/outdoor_rocks.html"));
    pub const EDITOR_DEMO: &str = include_str!(concat!(env!("OUT_DIR"), "/editor_demo.html"));
    pub const INDEX: &str = include_str!(concat!(env!("OUT_DIR"), "/index.html"));

    /// Returns the HTML for the demo identified by slug (e.g. `"ship_flight"`).
    /// Returns `None` for unknown slugs.
    pub fn by_name(name: &str) -> Option<&'static str> {
        match name {
            "render_v2_basic" => Some(RENDER_V2_BASIC),
            "render_v2_sky" => Some(RENDER_V2_SKY),
            "debug_shapes" => Some(DEBUG_SHAPES),
            "indoor_room" => Some(INDOOR_ROOM),
            "indoor_corridor" => Some(INDOOR_CORRIDOR),
            "outdoor_night" => Some(OUTDOOR_NIGHT),
            "outdoor_canyon" => Some(OUTDOOR_CANYON),
            "indoor_cathedral" => Some(INDOOR_CATHEDRAL),
            "indoor_server_room" => Some(INDOOR_SERVER_ROOM),
            "outdoor_city" => Some(OUTDOOR_CITY),
            "outdoor_volcano" => Some(OUTDOOR_VOLCANO),
            "space_station" => Some(SPACE_STATION),
            "light_benchmark" => Some(LIGHT_BENCHMARK),
            "rc_benchmark" => Some(RC_BENCHMARK),
            "load_fbx" => Some(LOAD_FBX),
            "load_fbx_embedded" => Some(LOAD_FBX_EMBEDDED),
            "ship_flight" => Some(SHIP_FLIGHT),
            "simple_graph" => Some(SIMPLE_GRAPH),
            "outdoor_rocks" => Some(OUTDOOR_ROCKS),
            "editor_demo" => Some(EDITOR_DEMO),
            _ => None,
        }
    }
}

// ── demo modules (each compiled only when its feature is active) ──────────────

#[cfg(feature = "render_v2_basic")]
#[path = "../examples-wasm/render_v2_basic.rs"]
mod render_v2_basic;

#[cfg(feature = "render_v2_sky")]
#[path = "../examples-wasm/render_v2_sky.rs"]
mod render_v2_sky;

#[cfg(feature = "debug_shapes")]
#[path = "../examples-wasm/debug_shapes.rs"]
mod debug_shapes;

#[cfg(feature = "indoor_room")]
#[path = "../examples-wasm/indoor_room.rs"]
mod indoor_room;

#[cfg(feature = "indoor_corridor")]
#[path = "../examples-wasm/indoor_corridor.rs"]
mod indoor_corridor;

#[cfg(feature = "outdoor_night")]
#[path = "../examples-wasm/outdoor_night.rs"]
mod outdoor_night;

#[cfg(feature = "outdoor_canyon")]
#[path = "../examples-wasm/outdoor_canyon.rs"]
mod outdoor_canyon;

#[cfg(feature = "indoor_cathedral")]
#[path = "../examples-wasm/indoor_cathedral.rs"]
mod indoor_cathedral;

#[cfg(feature = "indoor_server_room")]
#[path = "../examples-wasm/indoor_server_room.rs"]
mod indoor_server_room;

#[cfg(feature = "outdoor_city")]
#[path = "../examples-wasm/outdoor_city.rs"]
mod outdoor_city;

#[cfg(feature = "outdoor_volcano")]
#[path = "../examples-wasm/outdoor_volcano.rs"]
mod outdoor_volcano;

#[cfg(feature = "space_station")]
#[path = "../examples-wasm/space_station.rs"]
mod space_station;

#[cfg(feature = "light_benchmark")]
#[path = "../examples-wasm/light_benchmark.rs"]
mod light_benchmark;

#[cfg(feature = "rc_benchmark")]
#[path = "../examples-wasm/rc_benchmark.rs"]
mod rc_benchmark;

#[cfg(feature = "load_fbx")]
#[path = "../examples-wasm/load_fbx.rs"]
mod load_fbx;

#[cfg(feature = "load_fbx_embedded")]
#[path = "../examples-wasm/load_fbx_embedded.rs"]
mod load_fbx_embedded;

#[cfg(feature = "ship_flight")]
#[path = "../examples-wasm/ship_flight.rs"]
mod ship_flight;

#[cfg(feature = "simple_graph")]
#[path = "../examples-wasm/simple_graph.rs"]
mod simple_graph;

#[cfg(feature = "outdoor_rocks")]
#[path = "../examples-wasm/outdoor_rocks.rs"]
mod outdoor_rocks;

#[cfg(feature = "editor_demo")]
#[path = "../examples-wasm/editor_demo.rs"]
mod editor_demo;

// ── WASM entry point ──────────────────────────────────────────────────────────
// Exactly one feature is active per build; that branch calls `launch`.

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen::prelude::wasm_bindgen(start)]
pub fn start() {
    #[cfg(feature = "render_v2_basic")]
    {
        helio_wasm::launch::<render_v2_basic::Demo>();
        return;
    }
    #[cfg(feature = "render_v2_sky")]
    {
        helio_wasm::launch::<render_v2_sky::Demo>();
        return;
    }
    #[cfg(feature = "debug_shapes")]
    {
        helio_wasm::launch::<debug_shapes::Demo>();
        return;
    }
    #[cfg(feature = "indoor_room")]
    {
        helio_wasm::launch::<indoor_room::Demo>();
        return;
    }
    #[cfg(feature = "indoor_corridor")]
    {
        helio_wasm::launch::<indoor_corridor::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_night")]
    {
        helio_wasm::launch::<outdoor_night::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_canyon")]
    {
        helio_wasm::launch::<outdoor_canyon::Demo>();
        return;
    }
    #[cfg(feature = "indoor_cathedral")]
    {
        helio_wasm::launch::<indoor_cathedral::Demo>();
        return;
    }
    #[cfg(feature = "indoor_server_room")]
    {
        helio_wasm::launch::<indoor_server_room::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_city")]
    {
        helio_wasm::launch::<outdoor_city::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_volcano")]
    {
        helio_wasm::launch::<outdoor_volcano::Demo>();
        return;
    }
    #[cfg(feature = "space_station")]
    {
        helio_wasm::launch::<space_station::Demo>();
        return;
    }
    #[cfg(feature = "light_benchmark")]
    {
        helio_wasm::launch::<light_benchmark::Demo>();
        return;
    }
    #[cfg(feature = "rc_benchmark")]
    {
        helio_wasm::launch::<rc_benchmark::Demo>();
        return;
    }
    #[cfg(feature = "load_fbx")]
    {
        helio_wasm::launch::<load_fbx::Demo>();
        return;
    }
    #[cfg(feature = "load_fbx_embedded")]
    {
        helio_wasm::launch::<load_fbx_embedded::Demo>();
        return;
    }
    #[cfg(feature = "ship_flight")]
    {
        helio_wasm::launch::<ship_flight::Demo>();
        return;
    }
    #[cfg(feature = "simple_graph")]
    {
        helio_wasm::launch::<simple_graph::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_rocks")]
    {
        helio_wasm::launch::<outdoor_rocks::Demo>();
        return;
    }
    #[cfg(feature = "editor_demo")]
    {
        helio_wasm::launch::<editor_demo::Demo>();
        return;
    }
}

// ── Native entry (for `cargo run -p helio-web-demos --features <name>`) ───────

#[cfg(not(target_arch = "wasm32"))]
pub fn main() {
    #[cfg(feature = "render_v2_basic")]
    {
        helio_wasm::launch::<render_v2_basic::Demo>();
        return;
    }
    #[cfg(feature = "render_v2_sky")]
    {
        helio_wasm::launch::<render_v2_sky::Demo>();
        return;
    }
    #[cfg(feature = "debug_shapes")]
    {
        helio_wasm::launch::<debug_shapes::Demo>();
        return;
    }
    #[cfg(feature = "indoor_room")]
    {
        helio_wasm::launch::<indoor_room::Demo>();
        return;
    }
    #[cfg(feature = "indoor_corridor")]
    {
        helio_wasm::launch::<indoor_corridor::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_night")]
    {
        helio_wasm::launch::<outdoor_night::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_canyon")]
    {
        helio_wasm::launch::<outdoor_canyon::Demo>();
        return;
    }
    #[cfg(feature = "indoor_cathedral")]
    {
        helio_wasm::launch::<indoor_cathedral::Demo>();
        return;
    }
    #[cfg(feature = "indoor_server_room")]
    {
        helio_wasm::launch::<indoor_server_room::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_city")]
    {
        helio_wasm::launch::<outdoor_city::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_volcano")]
    {
        helio_wasm::launch::<outdoor_volcano::Demo>();
        return;
    }
    #[cfg(feature = "space_station")]
    {
        helio_wasm::launch::<space_station::Demo>();
        return;
    }
    #[cfg(feature = "light_benchmark")]
    {
        helio_wasm::launch::<light_benchmark::Demo>();
        return;
    }
    #[cfg(feature = "rc_benchmark")]
    {
        helio_wasm::launch::<rc_benchmark::Demo>();
        return;
    }
    #[cfg(feature = "load_fbx")]
    {
        helio_wasm::launch::<load_fbx::Demo>();
        return;
    }
    #[cfg(feature = "load_fbx_embedded")]
    {
        helio_wasm::launch::<load_fbx_embedded::Demo>();
        return;
    }
    #[cfg(feature = "ship_flight")]
    {
        helio_wasm::launch::<ship_flight::Demo>();
        return;
    }
    #[cfg(feature = "simple_graph")]
    {
        helio_wasm::launch::<simple_graph::Demo>();
        return;
    }
    #[cfg(feature = "outdoor_rocks")]
    {
        helio_wasm::launch::<outdoor_rocks::Demo>();
        return;
    }
    #[cfg(feature = "editor_demo")]
    {
        helio_wasm::launch::<editor_demo::Demo>();
        return;
    }

    eprintln!("helio-web-demos: no feature selected. Pass --features <demo_name>.");
}
